spring:
  liquibase:
    change-log: classpath:/db/changelog/master.xml
  datasource:
    url: jdbc:h2:mem:test
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true